CREATE TABLE HOTEL (
    HOTEL_ID NUMBER,
    CONSTRAINT HOTEL_ID_PK PRIMARY KEY (HOTEL_ID),
    NAME NVARCHAR2(100) NOT NULL,
    COUNTRY NVARCHAR2(100) NOT NULL,
    CITY NVARCHAR2(100) NOT NULL,
    STREET NVARCHAR2(100) NOT NULL
);