CREATE TABLE FILES (
    ID NUMBER,
    CONSTRAINT FILES_ID_PK PRIMARY KEY (ID),
    FILE_NAME NVARCHAR2(50) NOT NULL,
    FILE_FORMAT NVARCHAR2(50) NOT NULL,
    FILE_SIZE NUMBER NOT NULL,
    STORAGE_ID NUMBER,
    CONSTRAINT STORAGE_ID_FK FOREIGN KEY (STORAGE_ID) REFERENCES STORAGES (ID)
);