CREATE TABLE USERSS (
    ID NUMBER,
    CONSTRAINT USER_ID_PK PRIMARY KEY (ID),
    USER_NAME NVARCHAR2(100) NOT NULL,
    USER_PASSWORD NVARCHAR2(10) NOT NULL,
    COUNTRY NVARCHAR2(20) NOT NULL,
    USER_TYPE NVARCHAR2(10) NOT NULL
);

CREATE SEQUENCE USERSS_SEQ MINVALUE 1 MAXVALUE 100  START WITH 1 INCREMENT BY 1;