CREATE TABLE ORDERSS (
    ID NUMBER,
    CONSTRAINT ORDERSS_ID_PK PRIMARY KEY (ID),
    USER_ID NUMBER,
    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERSS(ID),
    ROOMM_ID NUMBER,
    CONSTRAINT ROOMM_ID_FK FOREIGN KEY (ROOMM_ID) REFERENCES ROOM(ID),
    DATE_FROM DATE,
    DATE_TO DATE,
    MONEY_PAID NUMBER
);

CREATE SEQUENCE ORDERSS_SEQ MINVALUE 1 MAXVALUE 100  START WITH 1 INCREMENT BY 1;